name: PHP CI3 Test & Lint

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    linux_tests:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: nightlight

        strategy:
            fail-fast: true
            matrix:
                php: ['7.4']
                stability: [prefer-lowest, prefer-stable]

        name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, memcached
                  tools: composer:v2
                  coverage: none

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v2
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            - name: Install dependencies
              if: steps.composer-cache.outputs.cache-hit != 'true'
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Create .env file
              run: |
                touch .env
                echo DB_HOSTNAME=localhost >> .env
                echo DB_USERNAME=root >> .env
                echo DB_PASSWORD="" >> .env
                echo DB_DATABASE=nightlight >> .env
                echo DB_DRIVER=mysqli >> .env
                echo MIGRATIONS_ENABLED=true >> .env
                cat .env

            - name: Run linter
              run: composer run-script ci-lint

            - name: Run migrations
              run: composer run-script migrate

            - name: Run test suite
              run: composer run-script test
